/**
 * The offline airport table: code to city, country and zone.
 *
 * A departure time is local to its airport, so turning one into an instant
 * needs the airport's zone, and resolving "JFK" to New York is what lets a
 * card speak in words a person recognizes. The table ships with the app like
 * every other asset and nothing is ever looked up over the network.
 * Generated by tools/build-airports.mjs from public datasets; loaded lazily
 * so the main bundle stays lean.
 */

export interface Airport {
  code: string;
  city: string;
  country: string;
  zone: string;
}

type Row = [code: string, city: string, country: string, zone: string];

let tablePromise: Promise<Map<string, Airport>> | null = null;

function table(): Promise<Map<string, Airport>> {
  if (!tablePromise) {
    tablePromise = import("./tables/airports.json").then((mod) => {
      const rows = (mod.default ?? mod) as Row[];
      const map = new Map<string, Airport>();
      for (const [code, city, country, zone] of rows) {
        map.set(code, { code, city, country, zone });
      }
      return map;
    });
  }
  return tablePromise;
}

/** The airport a code names, or null for one the table does not know. */
export async function lookupAirport(code: string): Promise<Airport | null> {
  if (!/^[A-Za-z]{3}$/.test(code)) {
    return null;
  }
  return (await table()).get(code.toUpperCase()) ?? null;
}
