-- Generated by apps/server/scripts/export-sqlite-schema.ts from apps/server/src/db.ts. Do not edit.
CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      login_key_digest TEXT NOT NULL,
      key_attributes TEXT NOT NULL,
      last_seq BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
CREATE TABLE IF NOT EXISTS folders (
      id TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      parent_id TEXT,
      encrypted_key TEXT NOT NULL,
      encrypted_meta TEXT NOT NULL,
      deleted BIGINT NOT NULL DEFAULT 0,
      update_seq BIGINT NOT NULL,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS folders_user_seq ON folders(user_id, update_seq);
    CREATE INDEX IF NOT EXISTS folders_parent ON folders(user_id, parent_id);
    CREATE TABLE IF NOT EXISTS files (
      id TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      folder_id TEXT,
      encrypted_key TEXT NOT NULL,
      encrypted_meta TEXT NOT NULL,
      size BIGINT NOT NULL DEFAULT 0,
      thumb_size BIGINT NOT NULL DEFAULT 0,
      uploaded BIGINT NOT NULL DEFAULT 0,
      trashed BIGINT NOT NULL DEFAULT 0,
      deleted BIGINT NOT NULL DEFAULT 0,
      update_seq BIGINT NOT NULL,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS files_user_seq ON files(user_id, update_seq);
    CREATE INDEX IF NOT EXISTS files_folder ON files(user_id, folder_id);
    CREATE TABLE IF NOT EXISTS shares (
      token TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      file_id TEXT NOT NULL REFERENCES files(id),
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS shares_owner ON shares(user_id);
    CREATE INDEX IF NOT EXISTS shares_file ON shares(file_id);
    CREATE TABLE IF NOT EXISTS file_requests (
      token TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      folder_id TEXT,
      encrypted_meta TEXT NOT NULL,
      expires_at BIGINT,
      revoked BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS file_requests_owner ON file_requests(user_id);
    CREATE TABLE IF NOT EXISTS request_uploads (
      id TEXT PRIMARY KEY,
      request_token TEXT NOT NULL REFERENCES file_requests(token),
      user_id BIGINT NOT NULL REFERENCES users(id),
      sealed_key TEXT NOT NULL,
      encrypted_meta TEXT NOT NULL,
      size BIGINT NOT NULL DEFAULT 0,
      thumb_size BIGINT NOT NULL DEFAULT 0,
      uploaded BIGINT NOT NULL DEFAULT 0,
      consumed BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS request_uploads_owner ON request_uploads(user_id, uploaded, consumed);
    CREATE TABLE IF NOT EXISTS file_versions (
      file_id TEXT NOT NULL REFERENCES files(id),
      user_id BIGINT NOT NULL REFERENCES users(id),
      generation BIGINT NOT NULL,
      size BIGINT NOT NULL,
      encrypted_meta TEXT NOT NULL,
      created_at BIGINT NOT NULL,
      PRIMARY KEY (file_id, generation)
    );
    CREATE INDEX IF NOT EXISTS file_versions_owner ON file_versions(user_id);
    CREATE TABLE IF NOT EXISTS auth_throttle (
      key TEXT PRIMARY KEY,
      failures BIGINT NOT NULL DEFAULT 0,
      blocked_until BIGINT NOT NULL DEFAULT 0,
      last_failure BIGINT NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS invites (
      token TEXT PRIMARY KEY,
      created_by BIGINT NOT NULL REFERENCES users(id),
      created_at BIGINT NOT NULL,
      expires_at BIGINT,
      used_by BIGINT,
      used_at BIGINT
    );
    CREATE TABLE IF NOT EXISTS upload_sessions (
      id TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      file_id TEXT NOT NULL,
      blob_key TEXT NOT NULL,
      handle TEXT NOT NULL,
      declared_bytes BIGINT NOT NULL,
      base_generation BIGINT NOT NULL,
      base_uploaded BIGINT NOT NULL,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS upload_sessions_file ON upload_sessions(file_id);
    CREATE TABLE IF NOT EXISTS upload_parts (
      session_id TEXT NOT NULL REFERENCES upload_sessions(id),
      part_no BIGINT NOT NULL,
      etag TEXT,
      bytes BIGINT NOT NULL,
      PRIMARY KEY (session_id, part_no)
    );
    CREATE TABLE IF NOT EXISTS collab_invites (
      token TEXT PRIMARY KEY,
      file_id TEXT NOT NULL REFERENCES files(id),
      owner_id BIGINT NOT NULL REFERENCES users(id),
      role TEXT NOT NULL,
      expires_at BIGINT,
      revoked BIGINT NOT NULL DEFAULT 0,
      claimed_by BIGINT,
      claimed_at BIGINT,
      granted BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS collab_invites_owner ON collab_invites(owner_id, granted, revoked);
    CREATE INDEX IF NOT EXISTS collab_invites_file ON collab_invites(file_id);
    CREATE TABLE IF NOT EXISTS session_keys (
      id TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      key TEXT NOT NULL,
      token_epoch BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS session_keys_user ON session_keys(user_id);
    CREATE TABLE IF NOT EXISTS channel_messages (
      file_id TEXT NOT NULL,
      seq BIGINT NOT NULL,
      sender TEXT NOT NULL,
      payload TEXT NOT NULL,
      bytes BIGINT NOT NULL,
      created_at BIGINT NOT NULL,
      PRIMARY KEY (file_id, seq)
    );
    CREATE TABLE IF NOT EXISTS channel_state (
      file_id TEXT PRIMARY KEY,
      last_seq BIGINT NOT NULL DEFAULT 0,
      snapshot_generation BIGINT NOT NULL DEFAULT 0,
      snapshot_seq BIGINT NOT NULL DEFAULT 0,
      bytes BIGINT NOT NULL DEFAULT 0,
      member_counter BIGINT NOT NULL DEFAULT 0,
      content_generation BIGINT NOT NULL DEFAULT 0,
      content_channel_seq BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS collab_tickets (
      ticket TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      file_id TEXT NOT NULL,
      expires_at BIGINT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS channel_presence (
      file_id TEXT NOT NULL,
      conn_id TEXT NOT NULL,
      pod_id TEXT NOT NULL,
      user_id BIGINT NOT NULL,
      user_index BIGINT NOT NULL,
      role TEXT,
      joined_at BIGINT NOT NULL,
      last_seen BIGINT NOT NULL,
      PRIMARY KEY (file_id, conn_id)
    );
    CREATE INDEX IF NOT EXISTS channel_presence_file ON channel_presence(file_id, last_seen);
    CREATE TABLE IF NOT EXISTS file_collaborators (
      file_id TEXT NOT NULL REFERENCES files(id),
      user_id BIGINT NOT NULL REFERENCES users(id),
      owner_id BIGINT NOT NULL REFERENCES users(id),
      role TEXT NOT NULL,
      sealed_key TEXT NOT NULL,
      key_epoch BIGINT NOT NULL DEFAULT 0,
      update_seq BIGINT NOT NULL,
      revoked BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL,
      PRIMARY KEY (file_id, user_id)
    );
    CREATE INDEX IF NOT EXISTS file_collaborators_user ON file_collaborators(user_id, update_seq);
    CREATE INDEX IF NOT EXISTS file_collaborators_file ON file_collaborators(file_id, revoked);
    CREATE TABLE IF NOT EXISTS auth_challenges (
      id TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      kind TEXT NOT NULL,
      secret_digest TEXT NOT NULL,
      expires_at BIGINT NOT NULL,
      used BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS auth_challenges_user ON auth_challenges(user_id, kind, created_at);
    CREATE TABLE IF NOT EXISTS pods (
      pod_id TEXT PRIMARY KEY,
      last_seen BIGINT NOT NULL
    );
