/**
 * Writes the server's SQLite schema and additive column migrations into
 * the on-device backend crate, so both open the same tables. The server
 * test test/localschema.test.ts fails when the committed copy falls
 * behind src/db.ts.
 *
 *   pnpm --filter @engramer/server export:schema
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { COLUMN_MIGRATIONS, COMMON_SCHEMA, SQLITE_USERS_TABLE } from "../src/db.js";

export const SCHEMA_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "crates",
  "engram-local",
  "schema",
);

export function renderSchema(): string {
  return (
    "-- Generated by apps/server/scripts/export-sqlite-schema.ts from apps/server/src/db.ts. Do not edit.\n" +
    `${SQLITE_USERS_TABLE.trim()}\n${COMMON_SCHEMA.trim()}\n`
  );
}

export function renderMigrations(): string {
  return `${JSON.stringify(COLUMN_MIGRATIONS, null, 2)}\n`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  mkdirSync(SCHEMA_DIR, { recursive: true });
  writeFileSync(join(SCHEMA_DIR, "sqlite-schema.sql"), renderSchema());
  writeFileSync(join(SCHEMA_DIR, "column-migrations.json"), renderMigrations());
  console.log(`export-sqlite-schema: wrote ${SCHEMA_DIR}`);
}
